pipeline {
    agent {
        label 'default'
    }
    stages {
        stage('Build') {
            steps {
                container('maven-jdk9') {
                    sh 'mvn -B -DskipTests clean package'
                }
            }
        }
        stage('Test') {
            steps {
                container('maven-jdk9') {
                    sh 'mvn test'
                }
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                container('maven-jdk9') {
                    sh './jenkins/scripts/deliver.sh'
                }
            }
        }
    }
}
